# This workflow builds a Python executable (.exe) file using pyinstaller
# and performs syntax checking using flake8

name: Build Python Executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Syntax check with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build executable with pyinstaller
      run: pyinstaller --onefile main.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: python-executable
        path: dist/main
